name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-snake.svg with modern mint neon style
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Luiz8734
          outputs: |
            snake-output/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#10b981&color_dots=#7c3aed,#8b5cf6,#a78bfa,#c4b5fd,#e0e7ff
            snake-output/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#10b981&color_dots=#7c3aed,#8b5cf6,#a78bfa,#c4b5fd,#e0e7ff

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: snake-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
