name: generate animation

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # Permite executar manualmente
  workflow_dispatch:

  # Roda em todo push na branch main (ou troque para master se for o caso)
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Gera os arquivos SVG da cobrinha com estilo personalizado
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Luiz8734
          outputs: |
            snake-output/github-contribution-grid-snake.svg?palette=dracula&color_snake=#00ffff&color_dots=#2d2d2d,#5c5c5c,#9c9c9c,#cfcfcf,#ffffff
            snake-output/github-contribution-grid-snake-dark.svg?palette=dracula&color_snake=#00ffff&color_dots=#2d2d2d,#5c5c5c,#9c9c9c,#cfcfcf,#ffffff

      # Faz push dos SVGs para a branch output
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: snake-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
